name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # Runs every 15 minutes
  workflow_dispatch:          # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Streamlit app
        run: curl -s https://movie-recommendation-3.streamlit.app/ > /dev/null
